version: "3.8"

services:
  mini-wallet:
    platform: linux/amd64
    ports:
        - 3000:3000
    build:
        context: .
        dockerfile: Dockerfile
    container_name: mini-wallet
    env_file:
        - docker.env
    volumes:
        - ./:/go/src/mini-wallet
    networks:
      - local
    depends_on:
      redis: 
        condition: service_healthy
      postgres:
        condition: service_healthy
  postgres:
    container_name: postgres
    image: postgres:12.0-alpine
    environment:
      POSTGRES_DB: mini-wallet
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/mini-wallet
    volumes:
      - .docker/postgres-data:/var/lib/postgresql/data/mini-wallet
    ports:
      - "5432:5432"
    networks:
      - local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    container_name: redis
    image: redis:7.0.0-alpine
    ports:
      - "6379:6379"
    networks:
      - local
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  uploads:
networks:
  local:
    driver: bridge